apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app-deployment
  labels:
    app: node-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-web-app
  template:
    metadata:
      name: node-web-app
      labels:
        app: node-web-app
    spec:
      containers:
        - name: node-web-app
          image: containerregistry11235.azurecr.io/nodejs-web-app:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-web-app-svc
spec:
  selector:
    app: node-web-app
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer